#!/usr/bin/python
'''
Replaces the spaces in the input file with a single tab.
'''
input_file=open('arVOG_file.txt', 'r')
output_file=open('arVOG_file.tab', 'a')
for line in input_file:
	words=line.rstrip()
	words=words.replace(' - ',' ')
	names=words.replace(' ','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')	
	output_file.write('%s\n'% names)
input_file=open('euVOG_file.txt', 'r')
output_file=open('euVOG_file.tab', 'a')
for line in input_file:
	words=line.rstrip()
	words=words.replace(' - ',' ')
	names=words.replace(' ','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')	
	output_file.write('%s\n'% names)
input_file=open('baPOG_file.txt', 'r')
output_file=open('baPOG_file.tab', 'a')
for line in input_file:
	words=line.rstrip()
	words=words.replace(' - ',' ')
	names=words.replace(' ','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')
	names=names.replace('\t\t','\t')	
	output_file.write('%s\n'% names)